### ISSUE TITLE
Kermits 126

### ISSUE THREAD

**Issue by Joseph-Burke** [descholar-ceo/youtube-player-page#2]
Share button - add a background image to the button or insert an <img> within the button element to achieve a better effect. Use margins and positioning to shift the position slightly.

Using a button tag doesn't mean it needs to 'look' like a button. It can be styled to match the appearance of the button on YouTube.

The page doesn't adapt to different screen sizes very well. On Brandon's screen, elements overlap, while on others', there is too wide a gap between elements. Responsive web design can be achieved by using different units of length.

A lot of CSS type selectors.

Positive: sticky header is a nice touch, matches the behaviour of YouTube's actual page.

Really nice structure and good work, some slight extra cosmetic changes would take it to the next level.

**Comment by descholar-ceo** [comment]
I like this review and concerns, @Joseph-Burke , We will manage to work on all feedback and close the issue soon. Thanks a lot!
